name: Android CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-for-changes:
    runs-on: self-hosted

    # skip ci 커밋 필터링
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, 'update coverage badges')"

    outputs:
      source_changes: ${{ steps.check_changes.outputs.any_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for source changes
        uses: tj-actions/changed-files@v42
        id: check_changes
        with:
          files_ignore: |
            **.md
            .idea/**
            .github/**
            .claude/**

  build:
    needs: check-for-changes
    if: needs.check-for-changes.outputs.source_changes == 'true'
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK (for self-hosted)
        if: runner.environment == 'self-hosted'
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Generate coverage reports for Debug variants
        run: ./gradlew createDebugCombinedCoverageReport

      - name: Display local test coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          title: Combined test coverage report
          min-coverage-overall: 70
          min-coverage-changed-files: 80
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/*Report.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: c9a0adeca134526611f8990962be022b
          filename: coverage.json
          label: Coverage
          message: ${{ steps.jacoco.outputs.coverage-overall }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ steps.jacoco.outputs.coverage-overall }}

      - name: Generate branches badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: c9a0adeca134526611f8990962be022b
          filename: branches.json
          label: Branches
          message: ${{ steps.jacoco.outputs.coverage-branches }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ steps.jacoco.outputs.coverage-branches }}